en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "All content licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/), unless otherwise noted. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our [Trademark Usage](https://www.linuxfoundation.org/trademark-usage) page. Linux is a registered trademark of Linus Torvalds. [Privacy Policy](https://www.linuxfoundation.org/privacy) and [Terms of Use](https://www.linuxfoundation.org/terms). [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "DevRel Foundation - A community of practitioners who aim to elevate the professional practice of developer relations"
  params:
    description: "DevRel Foundation exists to elevate the professional practice of developer relations and increase awareness of it as a driver of business value"
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: ""
      help_url: ""
    ### calls to action ###

    ###main_cta:
      ###text: "Get Involved"
      ###link: "/get-involved/"
    footer_cta:
      text: "Get Involved"
      link: "/get-involved/"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 1
    - identifier: "about-us"
      name: "About DRF"
      url: "/about/about-us/"
      weight: 1
      parent: "about"
    - identifier: "code-of-conduct"
      name: "Code of Conduct"
      url: "/about/code-of-conduct/"
      weight: 1
      parent: "about"
    - identifier: "charter"
      name: "Charter"
      url: "/about/charter/"
      weight: 1
      parent: "about"
    - identifier: "brand"
      name: "Brand"
      url: "/about/brand/"
      weight: 1
      parent: "about"
    - identifier: "contact"
      name: "Contact"
      url: "/about/contact/"
      weight: 1
      parent: "about"
    - identifier: "team"
      name: "Team"
      url: "/about/team/"
      weight: 1
      parent: "about"
    - identifier: "resources"
      name: "Resources"
      url: "/resources/"
      weight: 2
    - identifier: "working-groups"
      name: "Working Groups"
      url: "/working-groups/"
      weight: 3
    - identifier: "FAQ"
      name: "FAQ"
      url: "/faqs/"
      weight: 4

