######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/img/logo.svg"
logo_on_black: "/img/logo_white.svg"
custom_js: []
custom_css: []

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/img/social-share.jpg"]

github:
  repo_url: "https://github.com/DevRel-Foundation/website"
  show_edit_link: true

social_links:
  devstats: ""
  discord: ""
  facebook: ""
  flickr: ""
  github: "https://github.com/DevRel-Foundation"
  instagram: ""
  landscape: ""
  linkedin: "https://www.linkedin.com/company/devrel-foundation/"
  mastodon: ""
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  youtube: ""

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: false

# Google Maps API key for people_map shortcode
google_maps_api_key: "AIzaSyD5FrFpAN6jniMZTnQbTLkGGDSLH7wl5Wc"