[build]
publish = "public"
command = "make production-build"

[build.environment]
NODE_VERSION = "18.14.0"
HUGO_VERSION = "0.126.1"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"
